
import Nav from "../components/Nav";
import "../styles/globals.css";
import { Toaster } from 'react-hot-toast';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main>
          <Nav />
          {children}
          <Toaster />
        </main>
      </body>

    </html >
  )
}
